# Generated by Django 3.1.7 on 2021-03-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departaments',
            fields=[
                ('DepartamentId', models.AutoField(primary_key=True, serialize=False)),
                ('DepartamentName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employes',
            fields=[
                ('EmployeId', models.AutoField(primary_key=True, serialize=False)),
                ('EmployeName', models.CharField(max_length=100)),
                ('Departament', models.CharField(max_length=100)),
                ('DateOfJoining', models.DateField()),
                ('PhotoFileName', models.CharField(max_length=100)),
            ],
        ),
    ]
